/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lois_serialport_SerialPort */

#ifndef _Included_com_lois_serialport_SerialPort
#define _Included_com_lois_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lois_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_lois_serialport_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_lois_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lois_serialport_SerialPort_close
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_lois_serialport_SerialPort_read
  (JNIEnv *, jobject , jint , jbyteArray , jint );

JNIEXPORT jint JNICALL Java_com_lois_serialport_SerialPort_getFd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
